### ISSUE TITLE
panic when sorting an empty slice

### ISSUE THREAD

**Issue by nictuku** [patrickmn/sortutil#1]
Hi. Thanks for the nice library. 

There's a small bug that is easy to reproduce by passing an empty slice to be sorted. Example:

```
sortutil.DescByField([]foo{}, "fieldName")
```

The culprit is clearly:

v.Index(0).Type()

panic:

2012/03/16 21:30:52 http: panic serving [::1]:40153: reflect: slice index out of range
/home/yvesj/go/src/pkg/net/http/server.go:576 (0x48412a)
    _func_003: buf.Write(debug.Stack())
/home/yvesj/go/src/pkg/runtime/proc.c:1413 (0x4140ed)
    panic: reflect·call(d->fn, d->args, d->siz);
/home/yvesj/go/src/pkg/reflect/value.go:761 (0x4cad55)
    Value.Index: panic("reflect: slice index out of range")
/home/yvesj/go/src/pkg/github.com/pmylund/sortutil/sortutil.go:230 (0x4b63ed)
    com/pmylund/sortutil.New: T:        v.Index(0).Type(),
/home/yvesj/go/src/pkg/github.com/pmylund/sortutil/sortutil.go:274 (0x4b64f9)
    com/pmylund/sortutil.DescByField: New(slice, FieldGetter(name), Descending).Sort()
/home/yvesj/go/src/pkg/github.com/nictuku/magnets/supernode/popularity.go:75 (0x403630)
    popHandler: sortutil.DescByField([]downloadedItem{}, "count")
/home/yvesj/go/src/pkg/github.com/nictuku/magnets/supernode/popularity.go:46 (0x403922)
    _func_001: fn(w, r, p)
/home/yvesj/go/src/pkg/net/http/server.go:690 (0x478138)
    HandlerFunc.ServeHTTP: f(w, r)
/home/yvesj/go/src/pkg/net/http/server.go:924 (0x478fba)
    (_ServeMux).ServeHTTP: mux.handler(r).ServeHTTP(w, r)
/home/yvesj/go/src/pkg/net/http/server.go:656 (0x477f4b)
    (_conn).serve: handler.ServeHTTP(w, w.req)
/home/yvesj/go/src/pkg/runtime/proc.c:266 (0x412209)
    goexit: runtime·goexit(void)

**Comment by patrickmn** [comment]
Thank you, Yves! I'd missed that. It should be fixed in https://github.com/pmylund/sortutil/commit/c7ea60ca6fbb3e10b6f1b708494ee7ae229c9d70

**Comment by nictuku** [comment]
Thanks!

## 

Yves Junqueira http://cetico.org/about
